// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAYuFt-tbhwPwCwX5NYrldda1HWbylOwk',
    appId: '1:85494246572:android:96d341668cc1e862a7c309',
    messagingSenderId: '85494246572',
    projectId: 'artisan-handsandbrushes',
    storageBucket: 'artisan-handsandbrushes.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiRJa4_mCI7V0MS7349XB5ZxttQR3ipf0',
    appId: '1:85494246572:ios:98b6ca82a1c6625ea7c309',
    messagingSenderId: '85494246572',
    projectId: 'artisan-handsandbrushes',
    storageBucket: 'artisan-handsandbrushes.firebasestorage.app',
    iosClientId: '85494246572-d7hb3b6dks53pn7fl05hqp6gaivrd5gr.apps.googleusercontent.com',
    iosBundleId: 'com.artisan.handsandbrushes',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0rLgeZUH1Jd-fQe2jbU4MmX0SAkQiZGM',
    appId: '1:85494246572:web:bd1c1009a6b4a294a7c309',
    messagingSenderId: '85494246572',
    projectId: 'artisan-handsandbrushes',
    authDomain: 'artisan-handsandbrushes.firebaseapp.com',
    storageBucket: 'artisan-handsandbrushes.firebasestorage.app',
    measurementId: 'G-6GFKENKMRW',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7iNG6RNI80Fetfl6vvcpVXfWX8fJX9AM',
    appId: '1:417343899993:ios:ce836081b3121ad0dce448',
    messagingSenderId: '417343899993',
    projectId: 'artisan-5d023',
    storageBucket: 'artisan-5d023.firebasestorage.app',
    iosBundleId: 'com.artisan.artisan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAI9FsqfO5geIuQoyUH9yGmsnJpYtmuODM',
    appId: '1:417343899993:web:1f0e9815d5484ef7dce448',
    messagingSenderId: '417343899993',
    projectId: 'artisan-5d023',
    authDomain: 'artisan-5d023.firebaseapp.com',
    storageBucket: 'artisan-5d023.firebasestorage.app',
    measurementId: 'G-R71K585JW1',
  );
  // nothing
}